const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.LOS,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Browser.Acts.Reload,
		C3.Plugins.Sprite.Acts.AddInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{xp: 0},
	{Платформер: 0},
	{Стеження: 0},
	{Ross: 0},
	{Спрайт2: 0},
	{Спрайт3: 0},
	{ТвердеТіло: 0},
	{Спрайт4: 0},
	{Клавіатура: 0},
	{ПлиточнийФон: 0},
	{Спрайт5: 0},
	{Синусоїда: 0},
	{Спрайт6: 0},
	{Спрайт7: 0},
	{Спрайт8: 0},
	{Спрайт9: 0},
	{Спрайт10: 0},
	{Спрайт11: 0},
	{Текст: 0},
	{Спрайт12: 0},
	{Спрайт13: 0},
	{Спрайт14: 0},
	{Спрайт15: 0},
	{ПолеЗору: 0},
	{Enemy: 0},
	{ПлиточнийФон2: 0},
	{ПлиточнийФон3: 0},
	{ПлиточнийФон4: 0},
	{Браузер: 0},
	{Аудіо: 0},
	{Куля: 0},
	{Спрайт: 0},
	{Спрайт16: 0},
	{Спрайт17: 0},
	{Спрайт18: 0},
	{Миша: 0},
	{Спрайт19: 0},
	{Спрайт20: 0},
	{Спрайт21: 0},
	{Спрайт22: 0},
	{Спрайт23: 0},
	{Спрайт24: 0},
	{Спрайт25: 0},
	{Спрайт26: 0},
	{Спрайт27: 0},
	{Спрайт28: 0},
	{Спрайт29: 0},
	{двері: 0},
	{перезавантаженя: 0},
	{Спрайт30: 0},
	{Спрайт31: 0},
	{Спрайт32: 0},
	{Спрайт33: 0},
	{Спрайт34: 0},
	{Спрайт35: 0},
	{Спрайт36: 0},
	{Спрайт37: 0},
	{Спрайт38: 0},
	{Спрайт39: 0},
	{Спрайт40: 0},
	{Coins: 0}
];

self.InstanceType = {
	Ross: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Клавіатура: class extends self.IInstance {},
	ПлиточнийФон: class extends self.ITiledBackgroundInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	Спрайт11: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	Спрайт12: class extends self.ISpriteInstance {},
	Спрайт13: class extends self.ISpriteInstance {},
	Спрайт14: class extends self.ISpriteInstance {},
	Спрайт15: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	ПлиточнийФон2: class extends self.ITiledBackgroundInstance {},
	ПлиточнийФон3: class extends self.ITiledBackgroundInstance {},
	ПлиточнийФон4: class extends self.ITiledBackgroundInstance {},
	Браузер: class extends self.IInstance {},
	Аудіо: class extends self.IInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт16: class extends self.ISpriteInstance {},
	Спрайт17: class extends self.ISpriteInstance {},
	Спрайт18: class extends self.ISpriteInstance {},
	Миша: class extends self.IInstance {},
	Спрайт19: class extends self.ISpriteInstance {},
	Спрайт20: class extends self.ISpriteInstance {},
	Спрайт21: class extends self.ISpriteInstance {},
	Спрайт22: class extends self.ISpriteInstance {},
	Спрайт23: class extends self.ISpriteInstance {},
	Спрайт24: class extends self.ISpriteInstance {},
	Спрайт25: class extends self.ISpriteInstance {},
	Спрайт26: class extends self.ISpriteInstance {},
	Спрайт27: class extends self.ISpriteInstance {},
	Спрайт28: class extends self.ISpriteInstance {},
	Спрайт29: class extends self.ISpriteInstance {},
	двері: class extends self.ISpriteInstance {},
	перезавантаженя: class extends self.ISpriteInstance {},
	Спрайт30: class extends self.ISpriteInstance {},
	Спрайт31: class extends self.ISpriteInstance {},
	Спрайт32: class extends self.ISpriteInstance {},
	Спрайт33: class extends self.ISpriteInstance {},
	Спрайт34: class extends self.ISpriteInstance {},
	Спрайт35: class extends self.ISpriteInstance {},
	Спрайт36: class extends self.ISpriteInstance {},
	Спрайт37: class extends self.ISpriteInstance {},
	Спрайт38: class extends self.ISpriteInstance {},
	Спрайт39: class extends self.ISpriteInstance {},
	Спрайт40: class extends self.ISpriteInstance {}
}